### ISSUE TITLE
Listing 14.4: Trampoline for tail-call optimization in Java

### ISSUE THREAD

**Issue by thron7** [fcpbook/resources#5]
In the Java code there appears to be an issue. I think the line

  calc = call.thunk().get();

should be

  calc = call.thunk.get();

as 'thunk' is a field, not a method.

**Comment by charpov** [comment]
Java records automatically implement accessor methods. So, there is indeed a `thunk()` method that returns the `thunk` field, and the code works as it is. Of course, it would also work with `thunk` instead of `thunk()` by accessing the private field directly. I'm not sure what's best. Accessing record fields directly is weird, but using the accessor can be confusing, especially when new to Java records.

**Comment by thron7** [comment]
Ah, thanks, I have looked into records but wasn't aware of that.
